// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of the agent model discovery method.
 */
export type AgentListModelsResult = { models: Array<AgentModel> };

/**
 * One model an agent offers before any session exists.
 */
export type AgentModel = { id: string; displayName: string; default: boolean };

/**
 * Wire protocol used inside the bidirectional `agent/acp` notification.
 */
export type AgentProtocol = "acp";

/**
 * Host context handed to an agent when its underlying process starts.
 */
export type AgentStartContext = { cwd: string; hostVersion: string };

/**
 * Confirmation that a started agent is ready to receive ACP frames.
 */
export type AgentStartResult = { protocol: AgentProtocol; acpVersion: number };
